### ISSUE TITLE
Problemas con BEHS y ENABLE_TILANIMS en PACKED_MAP.

### ISSUE THREAD

**Issue by TartessosGames** [mojontwins/MK1#14]
Los tiles animados no hacen caso de los behs cuando se usan fuera de los 16 tiles del modo PACKED_MAP. Según donde se coloquen en la pantalla se comportan de una manera u otra. Si se colocan de la  línea Y2 para arriba se comportan como behs 0, pero si se colocan por debajo de Y2 hacen cosas raras: si el sprite cae sobre el tile animado se comporta como behs 8 y para al sprite como si fuera una plataforma, pero si lo toca por los lados o por debajo se comportan como un behs:  1 = Walkable and kills.

Al estar fuera de los 16 tiles de PACKED_MAP,  coloco los tiles animados como decoraciones o  con update_tile ();. En ambos casos dan el mismo problema. 

Ejemplo en el caso de update_tile ();    

 _x = 3; _y = 4; _t= 24;  _n = 0; 
update_tile ();

El tile alterna entre el 24 y el 25, pero su comportamiento es 8 si el sprite cae desde arriba y 1 si se toca de lado o por debajo. No hace caso a su behs asignado en config.h ni a  _n = 0;.

**Comment by mojontwins** [comment]
Gracias por reportar. Los tiles animados están muy poco depurados. ¡A ver si los dejamos finos! Necesito que me aclares algunas cosas:

- Dices "cuando se usan fuera de los 16 tiles del modo `UNPACKED_MAP`; el modo  `UNPACKED_MAP` tiene 48 tiles, así que no me queda muy clara cuál es la casuística. ¿Estás usando `PACKED_MAP` (16 tiles) y tus tiles animados están fuera de ese rango, es decir, con ID >= 16?
- ¿Cuál es la coordenada Y2?.

De todos modos creo que he encontrado el fallo, voy a intentar arreglarlo rápidamente :)

Gracias de nuevo.

**Comment by TartessosGames** [comment]
De nada y gracias a vosotros. 

Si, ya he corregido el reporte. Es en PACKED_MAP (16 tiles) y los tiles utilizados para animarlos que me dan problemas están por encima de 16. Aunque no probé usar tiles inferiores a 16, ni tampoco lo he comprobado en modo UNPACKED_MAP de 48. Pero Antonio me comentó que en ese modo funciona bien. Con coordenada Y2 me refería a la línea Y2 de la pantalla. Es decir, la línea horizontal 3.

**Comment by mojontwins** [comment]
Pues debería arreglarse con https://github.com/mojontwins/MK1/commit/dd3d824a82ccb35ddb9e766edeb8f8581d22aac6 . Al final era una tontería.

Gracias por el reporte. Cuando me confirmes que de verdad se arregló cerraré el issue.

**Comment by TartessosGames** [comment]
Perfect 👌
