### ISSUE TITLE
No suena el sonido: "6 - Matar a un enemigo" 

### ISSUE THREAD

**Issue by TartessosGames** [mojontwins/MK1#18]
Esto lo estuvimos viendo en el grupo de Telegram. El mismo problema se da en la Pestecera. Se arregla añadiendo: 

![668c63f3-53f4-424f-bbc8-10ed11055e7a](https://github.com/mojontwins/MK1/assets/159255327/6d47b6da-f22a-4389-96cb-8fc5931d6659)

**Comment by mojontwins** [comment]
Corregido con commit  #04694c4
¡Gracias!
