### ISSUE TITLE
Con  fixmappy no funciona PLAYER_PUSH_BOXES

### ISSUE THREAD

**Issue by TartessosGames** [mojontwins/MK1#20]
Probando la opción de empujar tiles con  fixmappy para que el tile de fondo y el que se sustituye al desplazar el tile desplazable no sean de color negro, me he encontrado con que el tile desplazable no se mueve. Probado en modo 128k + COMPRESSED_LEVELS.

**Comment by mojontwins** [comment]
¿Puedes hacerme llegar un proyecto de prueba con esta configuración para que lo revise? ¡Gracias!

Hay que tener en cuenta que fixmappy sólo hace restar 1 a los valores que mappy guarda en el mapa, ya que si el primer tile no es completamente negro mappy suma 1 al número de tile para que el "0" sea negro. Lo que quiero ver es si hay algún tipo de confusión con el baile de tiles arriba y abajo.

¡Gracias!

**Comment by TartessosGames** [comment]
Si, de hecho una de las pruebas que hice fué poniendo todos los behs de alrededor con behs 10, por si era eso, pero seguía sin funcionar.  Hoy ya no me da tiempo, estaré fuera hasta el miercoles. En cuanto regrese lo vuelvo a mirar y subo algún src de prueba.

**Comment by TartessosGames** [comment]
Pues al final era tema del baile de tiles. En las pruebas que hice con fixmappy también andaba guerreando con otro problema que he aprovechado para testear también y ahora reportaré (los behs a partir del tile 16 se desplazan en modo COMPRESSED_LEVELS) por lo que movía los behs y los tiles... Pero ya he comprobado que  PLAYER_PUSH_BOXES funciona bien con fixmappy tanto en PACKED como en UNPACKED_MAP. Cierro la issue.
