### ISSUE TITLE
Flags con comportamientos extraños

### ISSUE THREAD

**Issue by TartessosGames** [mojontwins/MK1#21]
Hay flags que tienen comportamientos extraños, como por ejemplo: ir marcando la posición en pixels del personaje, marca el número de frames, etc.

Flags con comportamientos extraños:
16- 17- 19-22-23-24-25-26-27-28-29-31-32-33  ( no sé si habrá alguna más, la 34 y 35 son las últimas testeadas y no daban problemas. Las estoy utilizando y el script funciona.)

La 18 y la 30 creo que únicamente se ponen en 1 al empezar el juego. Es posible utilizarlas sabiendo eso. Yo las estoy utilizando poniendolas a 0 al empezar el juego y no me están dando problemas.

Si no se pueden arreglar, podría ser útil indicar en la documentación o en config.h que dichas flags tienen esos comportamientos y no se pueden utilizar, ya que si se utilizan en un script no funcionará y te acabas peleando con el código hasta dar con que el problema proviene de las flags.  Las he testeado en vista lateral + modo 128k + COMPRESSED_LEVELS.  En la Pestecera también me ocurrió en vista genital un solo nivel: al portar "El Culto" a CPC  tuve que evitar alguna de las flags indicadas porque me daban problemas.

**Comment by mojontwins** [comment]
C no controla los limites de los arrays. Si un array tiene 16 elementos y accedes al 16, o al 17, lo que estarás leyendo es la memoria que hay detrás.

Si no defines MAX_FLAGS a un valor mayor de 16, el array de flags solo tiene 16 elementos, del 0 al 15. Si lees flags [18] estarás leyendo memoria más allá, que estará ocupada por otra variable.

Aquí hay un mapa de asignación de memoria que genera el compilador. Como ves, tras "flags" hay otras variables. Si te pasas de índice estarás leyendo estas variables:

```c
_FLAGS				= CFF2, G: MK1
_P_FACING			= CFF4, G: MK1
_P_FRAME			= CFF5, G: MK1
_PREGOTTEN			= CFF6, G: MK1
_HIT_H				= CFF7, G: MK1
_P_KILL_AMT			= CFF8, G: MK1
_HIT_V				= CFF9, G: MK1
_KILLED_OLD			= CFFA, G: MK1
_GPAUX				= CFFB, G: MK1
_MAP_ATTR			= CFFC, G: MK1
_ACTIVE				= D092, G: MK1
_P_CT_ESTADO			= D093, G: MK1
_LEVEL				= D094, G: MK1
_HOTSPOT_DESTROY		= D095, G: MK1
_X0				= D096, G: MK1
_Y0				= D097, G: MK1
_X1				= D098, G: MK1
_Y1				= D099, G: MK1
__N				= D09A, G: MK1
__T				= D09B, G: MK1
```

**Comment by TartessosGames** [comment]
Vale, imaginaba que sería algo así.

MAX_FLAGS lo tenía desactivado por que pensaba que lo que hacía era limitar el número de flags utilizables a la cifra indicada, para ahorrar memoria, velocidad, o lo que fuera... Gracias por la información!
