### ISSUE TITLE
Pregunta sobre el descompresor

### ISSUE THREAD

**Issue by fraespre** [mojontwins/MK1#5]
Buenos días,

Antes de nada, quería felicitaros por esta nueva versión del mk1.
Tengo una duda, revisando el código, veo que hacéis las compresiones usando el apultra. Sin embargo, desde dentro del juego, el descompresor utilizado parece (por los comentarios) que siga siendo el appack.

Por mi parte, he hecho los deberes y he revisado el código de z80 correspondiente al apultra y ... sustituyendo macros y suponiendo que habéis cambiado todas las etiquetas, he de decir que tiene un parecido razonable al descompresor del apultra. 
Pero como no estoy 100% seguro he preferido lanzaros la pregunta :-)

un saludo mojonil y gracias por adelantado !!!

**Comment by mojontwins** [comment]
Buenas
apultra no es más que un compresor del formato aplib que consigue mejor compresión que el compresor original apack.  Como el formato es el mismo, pudimos simplemente remplazar el compresor viejo apack.exe por un build de apultra.exe.
En resumen, apack y apultra son diferentes compresores de formato aplib y son intercambiables usando el mismo decompresor, pero apultra comprime levemente mejor.

**Comment by fraespre** [comment]
Muchas gracias @mojontwins ,

Siento decir que ayer seguí investigando y llegué a la misma conclusión. Me sabe mal haberos lanzado mi pregunta cuando yo mismo era capaz de responderla.

El tema es que estaba intentando utilizar esa misma rutina de descompresión y al probar, o me casca, o simplente no descomprime nada (blanco) ... En mi desesperación, pensé que podría ser debido a que no cuadraba el compresor con el descompresor.

Pero bueno, esto ya es tema que debo seguir trabajando por mi cuenta.
De nuevo muchas gracias y perdonad la intrusión.

**Comment by fraespre** [comment]
Copón !!! Si los de z88dk ya lo tienen en la nueva versión !!!
https://github.com/z88dk/z88dk/blob/master/include/_DEVELOPMENT/sdcc/compress/aplib.h

Estoy haciendo el tonto peleandome en integrar cosas que ya están integradas jajajajaja
